name: Deploy

on:
  workflow_run:
    workflows: ["Build"]
    types:
      - completed
    branches:
      - main
jobs:
  deploy:
    name: Deploy on Server
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Pull the Docker image
        run: docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/rest-api:latest

      - name: SSH and Deploy Docker Container
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SECRET }} #ssh key
          script: |
            sudo docker stop my-app || true
            sudo docker rm my-app || true
            
            sudo docker run -d \
              --name my-app \
              --network dsv-network \
              -p 80:8080 \
              -e SPRING_PROFILES_ACTIVE=prod \
              -e SPRING_DATASOURCE_URL="${{ secrets.PROD_DB_URL }}" \
              -e SPRING_DATASOURCE_USERNAME="${{ secrets.PROD_DB_USER }}" \
              -e SPRING_DATASOURCE_PASSWORD="${{ secrets.PROD_DB_PASSWORD }}" \
              -e EDENAI_API_KEY_PAID="${{ secrets.EDENAI_API_KEY_PAID }}" \
              -e GEMINI_API_KEY="${{ secrets.GEMINI_API_KEY }}" \
              -e SPRING_SQL_INIT_MODE=always \
              ${{ secrets.DOCKER_HUB_USERNAME }}/rest-api:latest